{+block}
# Dict.cn ads
cdn.dfile.cn/slot/

# Stupid China United Telecommunications Co. Ltd.
.wo.com.cn

# Fucking AD.
.kejet.net
.doubleclick.net
.googletagservices.com
.tanx.com

# Baidu sucks.
.baidu.com
.baidustatic.com

# Youku Sucks.
.youku.com

# Sohu Sucks.
.sohu.com

# Sougou Sucks.
.sougou.com

# 360 sucks.
.360.cn

# Netease sucks.
.163.com

# Tencent sucks.
.qq.com
.imqq.com
.soso.com

# CNNIC sucks.
.cnnic.net.cn
.cnnic.cn

# Mall that should be fucked.
.jd.com
.dangdang.com
