###############################
# Privoxy Rules for Freedom.
###############################
{{alias}}
direct   = +forward-override{forward .}
goagent  = +forward-override{forward 127.0.0.1:8087}
tor      = +forward-override{forward-socks5t tor:9050 .}
ss       = +forward-override{forward-socks5t shadowsocks:1080 .}
ssh      = +forward-override{forward-socks5t 127.0.0.1:7070 .}

{direct}
/

{tor}
*.onion

{ss}
# Blog
.blogspot.*
.blogspot.com.*
.blogger.com
.hidemyass.com:80

# Social Networks
.fackbook.com
.twitter.com
.flickr.com

# PHP
.getcomposer.org

# programmer community
.suckless.org
.sourceforge.net
.sf.net
.bitbucket.org
.github.com
.puppetlabs.com
.docker.com
.zendesk.com
.kbd-project.org

# Linux Distro
.exherbo.org
.funtoo.org
.archlinux.org

# Google
.google.com
.googleusercontent.com
.googlevideo.com
.youtube.com
.ytimg.com
.ggpht.com
.google-analytics.com
.gstatic.com
.gmail.com

# DuckDuckGo
.duckduckgo.com

# License
.creativecommons.org

# Blog
.blogblog.com
.program-think.blogspot.com
.lcx.cc
.gfw.me
.felixcat.net
.jwz.org

# Font and APIs
.typekit.net
.googleapis.com
.cloudfont.net

# Security
.openvpn.net
.shadowsocks.org
.shadowsocks.net
.torproject.org
.ip-check.info
.anonymous-proxy-server.net

# Cracker

# Misc
.4cdn.org
.4chan.org
.wp.com
.wordpress.com
.gravatar.com
.greatfire.org

{-block}
# Misc
