###############################
# Privoxy Rules for Freedom.
###############################
{{alias}}
direct   = +forward-override{forward .}
goagent  = +forward-override{forward 127.0.0.1:8087}
tor      = +forward-override{forward-socks5t tor:9050 .}
ss       = +forward-override{forward-socks5t shadowsocks:1080 .}
ssh      = +forward-override{forward-socks5t 127.0.0.1:7070 .}

{direct}
/

{tor}
*.onion

{ss}
## Blog
.blogspot.*
.blogspot.com.*
.blogger.com
.hidemyass.com:80
.blogblog.com
.program-think.blogspot.com
.lcx.cc
.gfw.me
.felixcat.net
.jwz.org

## Social Networks
.fackbook.com
.twitter.com
.flickr.com

## PHP
# composer is a tool for dependency management in PHP
.getcomposer.org
# PHP package archivist for composer
.packagist.org

# Programmer Community
.suckless.org
.kbd-project.org

## Code
.github.com
.sourceforge.net
.sf.net
.bitbucket.org

## Tech
.puppetlabs.com
.docker.com
.zendesk.com

# Linux Distribution
.funtoo.org
.exherbo.org
.archlinux.org

## Google
.google.com
.googleusercontent.com
.googlevideo.com
.youtube.com
.ytimg.com
.ggpht.com
.googleapis.com
.google-analytics.com
.gstatic.com
.gmail.com

# Other Search Engine
.duckduckgo.com

# License
.creativecommons.org

# Font and APIs
.typekit.net
.cloudfont.net

## Network
# encrypt network
.openvpn.net
.shadowsocks.org
.shadowsocks.net
.torproject.org
# tools
.ip-check.info
.anonymous-proxy-server.net
# anti-GFW
.greatfire.org

## Misc
# 4chan
.4cdn.org
.4chan.org
# wordpress
.wp.com
.wordpress.com
.gravatar.com

{-block}
