###############################
# Privoxy Rules for Freedom.
###############################
{{alias}}
direct   = +forward-override{forward .}
goagent  = +forward-override{forward 127.0.0.1:8087}
tor      = +forward-override{forward-socks5t tor:9050 .}
ss       = +forward-override{forward-socks5t shadowsocks:1080 .}
ssh      = +forward-override{forward-socks5t 127.0.0.1:7070 .}

{direct}
/

{tor}
*.onion

{ss}
## Blog
.blogspot.*
.blogspot.com.*
.blogger.com
.hidemyass.com:80
.blogblog.com
.program-think.blogspot.com
.lcx.cc
.gfw.me
.felixcat.net
.jwz.org
.miguelgrinberg.com

## Social Networks
.fackbook.com
.twitter.com
.flickr.com
.flask.pocoo.org
.python.org

## Programmer Community
.suckless.org
.kbd-project.org
.gitbook.com

## Code Hosting
.github.com
.sourceforge.net
.sf.net
.bitbucket.org

## Cloud Hosting
.digitalocean.com
.ssl.fastly.net

## Tech
.puppetlabs.com
.docker.com

## Linux Distribution
.exherbo.org
.archlinux.org

## Google
.google.com
.googleusercontent.com
.googlevideo.com
.youtube.com
.ytimg.com
.ggpht.com
.googleapis.com
.google-analytics.com
.gstatic.com
.gmail.com

## Other Search Engine
.duckduckgo.com

## Font and APIs
.typekit.net
.cloudfont.net

## Tools
.aircrack-ng.org

## License
.creativecommons.org

## Network
# classified network
.openvpn.net
.torproject.org
# Proxy
.shadowsocks.org
.shadowsocks.net
# anti-GFW
.greatfire.org
# tools
.ip-check.info
.anonymous-proxy-server.net

## Misc
# 4chan
.4chan.org
.4cdn.org

{-block}
